name: dionysus
short_name: dio
frequency: weekly
#trigger_day: Monday
trigger_day: Sunday
time_zone: US/Eastern
trigger_time_reminder: 2pm
#trigger_time_location: 4pm
trigger_time_location: 3:22pm
happy_hour_time: 5:50pm
personality:
  greetings:
    - Hi Peyton postdocs and grads!
    - Hello Peyton postdocs and grads!
    - Hello everyone,
    - Hi there,
  afterthought_prelude:
    - Oh and something that just crossed my mind,
    - By the way,
    - Also just fyi,
  goodbye:
    - Cheers,
    - Bye,
    - Thanks,
  mean_probability: 0.1
  # kindness probability = 1-mean_probability
  kind_bots:
    - kokoropos_bot


email:
  mail_server: mail.astro.princeton.edu  
  server_port: 587
  username: mathewm
  recipients:
    - mathewsyriac@gmail.com
  subject:
    - Peyton Happy Hour Tonight
#- postdoc@astro.princeton.edu
#- gradstupub@astro.princeton.edu
